{% set version = "1.4.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-desc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/desc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/desc/desc_{{ version }}.tar.gz
  sha256: 54468da73dd78fc9e7c565c41cfe3331802c2134b2e61a9ad197215317092f26

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-cli
    - r-rprojroot
  run:
    - r-base
    - r-r6
    - r-cli
    - r-rprojroot

test:
  commands:
    - $R -e "library('desc')"           # [not win]
    - "\"%R%\" -e \"library('desc')\""  # [win]

about:
  home: https://github.com/r-lib/desc#readme
  license: MIT
  summary: Tools to read, write, create, and manipulate DESCRIPTION files. It is intended for packages that create or manipulate other packages.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
