{% set version = "1.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-desc
  version: {{ version|replace("-", "_") }}

source:
  fn: desc_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/desc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/desc/desc_{{ version }}.tar.gz
  sha256: be80e448daf804e339a028288afa5be3d0f5b897f611ccd87de1243a94df84eb

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-assertthat
    - r-crayon
    - r-rprojroot
  run:
    - r-base
    - r-r6
    - r-assertthat
    - r-crayon
    - r-rprojroot

test:
  commands:
    - $R -e "library('desc')"           # [not win]
    - "\"%R%\" -e \"library('desc')\""  # [win]

about:
  home: https://github.com/r-lib/desc#readme
  license: MIT
  summary: Tools to read, write, create, and manipulate DESCRIPTION files. It is intended for packages that create or manipulate other packages.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
