appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: DEqfbG2UNuYnz2SKZxL0/218u4rwyvI8t1XEdJIRCNWzyBInBzPVJnLsD60W44R6H4RC3bzmI7CCh+z7BrMwHZbJ03xEquxbXQbGIEq2x8E/BjO3JqhvnVH5nXuRJaGT0zC+aEboMPrrSMrgki66NOQrcgcIGeRRArYSsOQ5a3LhNG7aXLVpudUEQPaCj25pIoTrcXHWbhjn/9EoEJlNLsyV7GHOlnWjaectW6C+rFb0AW9hqvqGU1hssPkrcsird6LSv3JwIq+4XkpgwjRgDyBY/EFhaBUA4i0h83pQ0j3GqztKUIeOLBWdluxIhoaSa0DWp3vdxuRUsLO7w9f4HJToalCMqqUqHu2JJiqOqnA7cMCoLvPILn+evyfGd9xlYnVU8W5L/bdLgRZPLz5p7qbihqUx4WmXVhoKpjkfVzHEFctVyRWd8BGxJOYOl9CPn32h0b/4cbGjxXw2aBSawqDoOwdfczjEPbGqwRPOLc/llSCeiXKCqjh8dUjrySIXaDu720EirOqG6ZuE8KdRLFsUhNLWA2KeuG2DrBNQ8ZzjYnlOdpFrV1y7fibu98eqrps/bXyu6/CPT9PMTCUPIpGuZbKvmnvUo8/yHDiEu683c7h3ZfiVNEeHYhNpC2aVVKm+vpGGjcKP2PPs/AxskmRwRBMIyeCDDLGFsSN74yE=
